---
# tasks file for nginx-role
- name: Install Nginx
  apt:
    name: nginx
    state: present

    

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes


- name: Copy index.html 
  copy:
    src: index.html
    dest: /var/www/html/